# -*- coding: utf-8 -*-
"""sports.ipl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJf9d-Uaj8HioFED30vvqADs18opbXDs
"""

!pip install pyTelegramBotAPI

!pip install python-telegram-bot==13.7

import telegram
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
import pandas as pd
# Load the dataset
dataset = pd.read_csv('/content/ipl.bcci.xlsx')
# Define the Telegram bot token
TOKEN = '6786280307:AAFfpDGW7km2X805VHtdpl97wd67YJ7XxV8'


# Create an instance of the Telegram bot
bot = telegram.Bot(token=TOKEN)
# Function to handle the '/start' command
def start(update, context):
    welcome_message = "Welcome to Game rules Bot! Please enter a Game name:"
    context.bot.send_message(chat_id=update.effective_chat.id, text=welcome_message)

# Function to handle user messages
def handle_message(update, context):
    user_input = update.message.text
    captians = dataset[dataset['team_names'] == user_input]['captians'].values
    if len(captians) > 0:
        response = f"The captians of {user_input} is {captians[0]}."
    else:
        response = "Sorry, I couldn't find the captain for the specified team."
    context.bot.send_message(chat_id=update.effective_chat.id, text=response)

# Create an instance of the Updater class
updater = Updater(token=TOKEN, use_context=True)

# Get the dispatcher to register handlers
dispatcher = updater.dispatcher

# Register handlers
dispatcher.add_handler(CommandHandler('start', start))
dispatcher.add_handler(MessageHandler(Filters.text, handle_message))

# Start the bot
updater.start_polling()